apiVersion: apps/v1
kind: Daemonset
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      tier: monitoring
      name: prometheus-exporter
  template:
    metadata:
      labels:
        tier: monitoring
        name: prometheus-exporter
    spec:
      containers:
      - name: promotheusprom
        image: prom/node-exporter
        ports:
        - containerPort: 80
