apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  labels:
    name: app-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-v1
  template:
    metadata:
      labels:
        app: app-v1
    spec:
      containers:
      - name: sample-ctr
        image: nginx
        ports:
        - containerPort: 80
        env:
          - name: CONF_USER
            valueFrom:
              configMapKeyRef:
                   name: user-credential
                   key: user
          - name: USR_PASSWD
            valueFrom:
              secretKeyRef:
                  name: user-pwd
                  key: password
        volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: pv-storage
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: test-pvc
                   