apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  labels:
    type: local
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
